services:
  clickhouse:
    image: ${CLICKHOUSE_IMAGE:-clickhouse/clickhouse-server}:${CLICKHOUSE_VERSION:-head}
    depends_on:
      zookeeper:
        condition: service_healthy
    volumes:
      - ./clickhouse_config_zookeeper.xml:/etc/clickhouse-server/config.d/clickhouse_config_zookeeper.xml
      - ./:/var/log/clickhouse-server/
    healthcheck:
      test: wget http://localhost:8123/ping
      interval: 3s
      timeout: 2s
      retries: 30
      start_period: 5s
  zookeeper:
    image: ${ZOOKEEPER_IMAGE:-zookeeper}:${ZOOKEEPER_VERSION:-latest}
    environment:
      ZOO_MY_ID: 1
      ZOO_4LW_COMMANDS_WHITELIST: "*"
    healthcheck:
      test: bash -c 'if [[ "$$(echo ruok | nc 127.0.0.1 2181)" == "imok" ]]; then exit 0; else exit 1; fi'
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 2s