---
global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: clickhouse
    static_configs:
      - targets: ['chnode1:9363', 'chnode2:9363', 'chnode3:9363', 'keeper1:9363', 'keeper2:9363', 'keeper3:9363']
