services:
  clickhouse:
    image: ${CLICKHOUSE_IMAGE:-clickhouse/clickhouse-server}:${CLICKHOUSE_VERSION:-head}
    depends_on:
      keeper:
        condition: service_healthy
    volumes:
      - ./clickhouse_config_keeper.xml:/etc/clickhouse-server/config.d/clickhouse_config_keeper.xml
      - ./:/var/log/clickhouse-server/
    healthcheck:
      test: wget http://localhost:8123/ping
      interval: 3s
      timeout: 2s
      retries: 30
      start_period: 5s
  keeper:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      keeper-0:
        condition: service_healthy
      keeper-1:
        condition: service_healthy
      keeper-2:
        condition: service_healthy
    healthcheck:
      test: bash -c 'if [ -e /var/run/nginx.pid ]; then exit 0; else exit 1; fi'
      interval: 3s
      timeout: 2s
      retries: 30
      start_period: 5s
  keeper-0:
    hostname: keeper-0
    extends:
      file: 3-nodes-keeper-base.yaml
      service: keeper
  keeper-1:
    hostname: keeper-1
    extends:
      file: 3-nodes-keeper-base.yaml
      service: keeper
  keeper-2:
    hostname: keeper-2
    extends:
      file: 3-nodes-keeper-base.yaml
      service: keeper