apiVersion: 1

deleteDatasources:
  - name: ClickHouse-chnode1
  - name: ClickHouse-chnode2
  - name: ClickHouse-chnode3

datasources:
  - name: ClickHouse-chnode1
    type: grafana-clickhouse-datasource
    isDefault: 1
    jsonData:
      defaultDatabase: default
      port: 9000
      server: chnode1
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: 
  - name: ClickHouse-chnode2
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      server: chnode2
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: 
  - name: ClickHouse-chnode3
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      server: chnode3
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: 
