---
global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: clickhouse
    static_configs:
      - targets: ['chnode_with_chkeeper1:9363', 'chnode_with_chkeeper2:9363', 'chnode_with_chkeeper3:9363', 'chnode4:9363', 'chnode5:9363', 'chnode6:9363']
